#!/bin/bash

# Check of the environments variable

guest_addr=`curl ifconfig.io 2>/dev/null` # should be replace by an environment variable for better performance
guest_user=`whoami`
ssh_port=`grep -e "Port\s" /etc/ssh/sshd_config | cut -d " " -f2`

if [ -z "$LC_VSCODE" ]
then
    echo LC_VSCODE is not defined
    echo It should be the path to the executable of vscode
    exit 1
fi

if [ -z "$LC_OS" ]
then
    echo Please provide a LC_OS variable
    echo Allowed values: "windows";"macos"
    exit 1
fi

if [ -z "$LC_USER" ]
then
    echo Please provide a LC_USER variable
    echo It should be the username where your vscode is installed
    exit 1
fi

if [ -z "$1" ]
then
    directory=`pwd` # If no arguments are provided the opened folder is the current one
else
    directory=`realpath $1` # I am always using 'code .' so i have to translate '.' to an absolute path
fi

if [ $LC_OS = "windows" ]
then
    # The following two line have to be merged into a single ssh command

    # Search for the host session
    host_session_id=`ssh -p 8822 $LC_USER@localhost "quser" | grep $LC_USER | awk '{ print $3}'` # sometime I saw that my session id is 1, other time it can be 16.

    # Start vscode
    ssh -p 8822 $LC_USER@localhost "psexec -s -i $host_session_id -d \"$LC_VSCODE\" --folder-uri=vscode-remote://ssh-remote+$guest_user@$guest_addr:$ssh_port/$directory" 1>/dev/null 2>/dev/null
elif [ $LC_OS = "macos" ]
then
    echo coucou
    ssh -p 8822 $LC_USER@localhost "$LC_VSCODE --folder-uri=vscode-remote://ssh-remote+$guest_user@$guest_addr:$ssh_port/$directory" 1>/dev/null 2>/dev/null

    # ssh -p 8822 $LC_USER@localhost "code --folder-uri=vscode-remote://ssh-remote+$guest_user@$guest_addr:$ssh_port/$directory" 1>/dev/null 2>/dev/null
else
    echo "your operating system \"$LC_OS\" is not supported"
fi