#!/bin/bash

# Check of the environments variable
if [ -z "$GUEST_ADDR" ]
then
    echo GUEST_ADDR is not defined
    exit 1
fi

if [ -z "$GUEST_USER" ]
then
    echo GUEST_USER is not defined
    exit 1
fi

if [ -z "$HOST_USER" ]
then
    echo HOST_USER is not defined
    exit 1
fi

if [ -z "$HOST_IP" ]
then
    echo HOST_IP is not defined
    exit 1
fi

if [ -z "$HOST_VSCODE_PATH" ]
then
    echo HOST_VSCODE_PATH is not defined
    exit 1
fi

# Search for the host session
host_session_id=`ssh $HOST_USER@$HOST_IP "quser" | grep $HOST_USER | awk '{ print $3}'` # sometime I saw that my session id is 1, other time it can be 2.

if [ -z "$1" ]
then
    directory=`pwd` # If no arguments are provided the opened folder is the current one
else
    directory=`realpath $1` # I am always using 'code .' so i have to translate '.' to an absolute path
fi

ssh $HOST_USER@$HOST_IP "psexec -s -i $host_session_id -d \"$HOST_VSCODE_PATH\" --folder-uri=vscode-remote://ssh-remote+$GUEST_USER@$GUEST_ADDR/$directory" 1>/dev/null 2>/dev/null